version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: master
    schedule:
      interval: monthly
      day: monday
      time: "01:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: monthly
      day: monday
      time: "01:30"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 0

