version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "01:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-and-patch:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:30"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
