/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type ProductContentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productContent";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  catalogNotice?: LocalizedText;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductContentReference
  >;
  defaultSeo?: Seo;
  sourceMetadata?: SourceMetadata;
};

export type SourceMetadata = {
  _type: "sourceMetadata";
  owner: string;
  sourceUrl?: string;
  lastReviewedAt: string;
  notes?: string;
};

export type Seo = {
  _type: "seo";
  title: LocalizedString;
  description: LocalizedText;
  image: AccessibleImage;
  noIndex?: boolean;
};

export type LocalizedText = {
  _type: "localizedText";
  id?: string;
  en?: string;
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type ProductCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productCategory";
};

export type ProductContent = {
  _id: string;
  _type: "productContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  commerceProductId: string;
  slug: Slug;
  name: LocalizedString;
  brand: BrandReference;
  category: ProductCategoryReference;
  audience: "salon" | "barber" | "both";
  shortDescription: LocalizedText;
  longDescription?: LocalizedText;
  howToUse?: LocalizedText;
  keyBenefits?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  recommendedFor?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  variants?: Array<{
    commerceVariantId: string;
    label: LocalizedString;
    _type: "productVariantContent";
    _key: string;
  }>;
  heroImage: AccessibleImage;
  gallery?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  infoSlides?: Array<{
    type:
      | "description"
      | "features"
      | "benefits"
      | "application"
      | "technology"
      | "ingredients";
    image: AccessibleImage;
    _type: "infoSlide";
    _key: string;
  }>;
  heroBrandImage: AccessibleImage;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductContentReference
  >;
  isNew?: boolean;
  status: "draft" | "active" | "archived";
  displayOrder: number;
  sourceMetadata?: SourceMetadata;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: LocalizedString;
};

export type LocalizedString = {
  _type: "localizedString";
  id?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  slug: Slug;
  description?: LocalizedText;
  status: "draft" | "active" | "archived";
  displayOrder: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  commerceBrandId: string;
  name: string;
  slug: Slug;
  summary?: LocalizedText;
  logo: AccessibleImage;
  heroImage: AccessibleImage;
  status: "draft" | "active" | "archived";
  displayOrder: number;
  sourceMetadata?: SourceMetadata;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductContentReference
  | SiteSettings
  | SourceMetadata
  | Seo
  | LocalizedText
  | BrandReference
  | ProductCategoryReference
  | ProductContent
  | SanityImageAssetReference
  | AccessibleImage
  | LocalizedString
  | Slug
  | ProductCategory
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/shared/lib/sanity/queries.ts
// Variable: catalogProductsQuery
// Query: *[  _type == "productContent" &&  status == "active" &&  brand->status == "active" &&  category->status == "active" &&  defined(commerceProductId) &&  defined(slug.current) &&  defined(heroImage.asset) &&  (defined(name.id) || defined(name.en)) &&  (defined(shortDescription.id) || defined(shortDescription.en))]  | order(displayOrder asc, name.id asc, name.en asc)  {  _id,  commerceProductId,  "slug": slug.current,  "name": coalesce(name.id, name.en),  "brand": brand->name,  "category": category->slug.current,  "categoryLabel": coalesce(category->title.id, category->title.en),  audience,  "description": coalesce(shortDescription.id, shortDescription.en),  "longDescription": coalesce(longDescription.id, longDescription.en),  "howToUse": coalesce(howToUse.id, howToUse.en),  "keyBenefits": keyBenefits[]{"value": coalesce(id, en)},  "recommendedFor": recommendedFor[]{"value": coalesce(id, en)},  "variants": variants[]{"id": commerceVariantId, "label": coalesce(label.id, label.en)},  isNew,  "image": heroImage.asset->url,  "gallery": gallery[].asset->url,  "infoSlides": infoSlides[]{type, "src": image.asset->url},  "heroImage": heroBrandImage.asset->url,  "relatedIds": relatedProducts[]->slug.current,  "seoTitle": coalesce(seo.title.id, seo.title.en),  "seoDescription": coalesce(seo.description.id, seo.description.en),  "seoImage": seo.image.asset->url,  "noIndex": coalesce(seo.noIndex, false)}
export type CatalogProductsQueryResult = Array<{
  _id: string;
  commerceProductId: string;
  slug: string;
  name: string | null;
  brand: string;
  category: string;
  categoryLabel: string | null;
  audience: "barber" | "both" | "salon";
  description: string | null;
  longDescription: string | null;
  howToUse: string | null;
  keyBenefits: Array<{
    value: string | null;
  }> | null;
  recommendedFor: Array<{
    value: string | null;
  }> | null;
  variants: Array<{
    id: string;
    label: string | null;
  }> | null;
  isNew: boolean | null;
  image: string;
  gallery: Array<string> | null;
  infoSlides: Array<{
    type:
      | "application"
      | "benefits"
      | "description"
      | "features"
      | "ingredients"
      | "technology";
    src: string;
  }> | null;
  heroImage: string;
  relatedIds: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: string | null;
  noIndex: boolean | false;
}>;

// Source: src/shared/lib/sanity/queries.ts
// Variable: catalogProductBySlugQuery
// Query: *[  _type == "productContent" &&  status == "active" &&  brand->status == "active" &&  category->status == "active" &&  defined(commerceProductId) &&  defined(slug.current) &&  defined(heroImage.asset) &&  (defined(name.id) || defined(name.en)) &&  (defined(shortDescription.id) || defined(shortDescription.en)) && slug.current == $slug][0]  {  _id,  commerceProductId,  "slug": slug.current,  "name": coalesce(name.id, name.en),  "brand": brand->name,  "category": category->slug.current,  "categoryLabel": coalesce(category->title.id, category->title.en),  audience,  "description": coalesce(shortDescription.id, shortDescription.en),  "longDescription": coalesce(longDescription.id, longDescription.en),  "howToUse": coalesce(howToUse.id, howToUse.en),  "keyBenefits": keyBenefits[]{"value": coalesce(id, en)},  "recommendedFor": recommendedFor[]{"value": coalesce(id, en)},  "variants": variants[]{"id": commerceVariantId, "label": coalesce(label.id, label.en)},  isNew,  "image": heroImage.asset->url,  "gallery": gallery[].asset->url,  "infoSlides": infoSlides[]{type, "src": image.asset->url},  "heroImage": heroBrandImage.asset->url,  "relatedIds": relatedProducts[]->slug.current,  "seoTitle": coalesce(seo.title.id, seo.title.en),  "seoDescription": coalesce(seo.description.id, seo.description.en),  "seoImage": seo.image.asset->url,  "noIndex": coalesce(seo.noIndex, false)}
export type CatalogProductBySlugQueryResult = {
  _id: string;
  commerceProductId: string;
  slug: string;
  name: string | null;
  brand: string;
  category: string;
  categoryLabel: string | null;
  audience: "barber" | "both" | "salon";
  description: string | null;
  longDescription: string | null;
  howToUse: string | null;
  keyBenefits: Array<{
    value: string | null;
  }> | null;
  recommendedFor: Array<{
    value: string | null;
  }> | null;
  variants: Array<{
    id: string;
    label: string | null;
  }> | null;
  isNew: boolean | null;
  image: string;
  gallery: Array<string> | null;
  infoSlides: Array<{
    type:
      | "application"
      | "benefits"
      | "description"
      | "features"
      | "ingredients"
      | "technology";
    src: string;
  }> | null;
  heroImage: string;
  relatedIds: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: string | null;
  noIndex: boolean | false;
} | null;

// Source: src/shared/lib/sanity/queries.ts
// Variable: catalogProductSlugsQuery
// Query: *[  _type == "productContent" &&  status == "active" &&  brand->status == "active" &&  category->status == "active" &&  defined(commerceProductId) &&  defined(slug.current) &&  defined(heroImage.asset) &&  (defined(name.id) || defined(name.en)) &&  (defined(shortDescription.id) || defined(shortDescription.en))].slug.current
export type CatalogProductSlugsQueryResult = Array<string>;

// Source: src/shared/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    siteTitle,    "catalogNotice": coalesce(catalogNotice.id, catalogNotice.en),    "seoTitle": coalesce(defaultSeo.title.id, defaultSeo.title.en),    "seoDescription": coalesce(defaultSeo.description.id, defaultSeo.description.en),    "seoImage": defaultSeo.image.asset->url,    "noIndex": coalesce(defaultSeo.noIndex, false)  }
export type SiteSettingsQueryResult = {
  siteTitle: string;
  catalogNotice: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: string | null;
  noIndex: boolean | false;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n  _type == "productContent" &&\n  status == "active" &&\n  brand->status == "active" &&\n  category->status == "active" &&\n  defined(commerceProductId) &&\n  defined(slug.current) &&\n  defined(heroImage.asset) &&\n  (defined(name.id) || defined(name.en)) &&\n  (defined(shortDescription.id) || defined(shortDescription.en))\n]\n  | order(displayOrder asc, name.id asc, name.en asc)\n  {\n  _id,\n  commerceProductId,\n  "slug": slug.current,\n  "name": coalesce(name.id, name.en),\n  "brand": brand->name,\n  "category": category->slug.current,\n  "categoryLabel": coalesce(category->title.id, category->title.en),\n  audience,\n  "description": coalesce(shortDescription.id, shortDescription.en),\n  "longDescription": coalesce(longDescription.id, longDescription.en),\n  "howToUse": coalesce(howToUse.id, howToUse.en),\n  "keyBenefits": keyBenefits[]{"value": coalesce(id, en)},\n  "recommendedFor": recommendedFor[]{"value": coalesce(id, en)},\n  "variants": variants[]{"id": commerceVariantId, "label": coalesce(label.id, label.en)},\n  isNew,\n  "image": heroImage.asset->url,\n  "gallery": gallery[].asset->url,\n  "infoSlides": infoSlides[]{type, "src": image.asset->url},\n  "heroImage": heroBrandImage.asset->url,\n  "relatedIds": relatedProducts[]->slug.current,\n  "seoTitle": coalesce(seo.title.id, seo.title.en),\n  "seoDescription": coalesce(seo.description.id, seo.description.en),\n  "seoImage": seo.image.asset->url,\n  "noIndex": coalesce(seo.noIndex, false)\n}\n': CatalogProductsQueryResult;
    '\n  *[\n  _type == "productContent" &&\n  status == "active" &&\n  brand->status == "active" &&\n  category->status == "active" &&\n  defined(commerceProductId) &&\n  defined(slug.current) &&\n  defined(heroImage.asset) &&\n  (defined(name.id) || defined(name.en)) &&\n  (defined(shortDescription.id) || defined(shortDescription.en))\n && slug.current == $slug][0]\n  {\n  _id,\n  commerceProductId,\n  "slug": slug.current,\n  "name": coalesce(name.id, name.en),\n  "brand": brand->name,\n  "category": category->slug.current,\n  "categoryLabel": coalesce(category->title.id, category->title.en),\n  audience,\n  "description": coalesce(shortDescription.id, shortDescription.en),\n  "longDescription": coalesce(longDescription.id, longDescription.en),\n  "howToUse": coalesce(howToUse.id, howToUse.en),\n  "keyBenefits": keyBenefits[]{"value": coalesce(id, en)},\n  "recommendedFor": recommendedFor[]{"value": coalesce(id, en)},\n  "variants": variants[]{"id": commerceVariantId, "label": coalesce(label.id, label.en)},\n  isNew,\n  "image": heroImage.asset->url,\n  "gallery": gallery[].asset->url,\n  "infoSlides": infoSlides[]{type, "src": image.asset->url},\n  "heroImage": heroBrandImage.asset->url,\n  "relatedIds": relatedProducts[]->slug.current,\n  "seoTitle": coalesce(seo.title.id, seo.title.en),\n  "seoDescription": coalesce(seo.description.id, seo.description.en),\n  "seoImage": seo.image.asset->url,\n  "noIndex": coalesce(seo.noIndex, false)\n}\n': CatalogProductBySlugQueryResult;
    '\n  *[\n  _type == "productContent" &&\n  status == "active" &&\n  brand->status == "active" &&\n  category->status == "active" &&\n  defined(commerceProductId) &&\n  defined(slug.current) &&\n  defined(heroImage.asset) &&\n  (defined(name.id) || defined(name.en)) &&\n  (defined(shortDescription.id) || defined(shortDescription.en))\n].slug.current\n': CatalogProductSlugsQueryResult;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    siteTitle,\n    "catalogNotice": coalesce(catalogNotice.id, catalogNotice.en),\n    "seoTitle": coalesce(defaultSeo.title.id, defaultSeo.title.en),\n    "seoDescription": coalesce(defaultSeo.description.id, defaultSeo.description.en),\n    "seoImage": defaultSeo.image.asset->url,\n    "noIndex": coalesce(defaultSeo.noIndex, false)\n  }\n': SiteSettingsQueryResult;
  }
}
